#!/usr/bin/env bash
set -Eeuo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd);export PATH="${HOME}/.local/bin:${PATH}";fixture=$root/content/fixtures/mf006r8-unknown-process.json;grammar=$root/config/visual-grammar.json;art=${MF_ARTIFACT_DIR:-$root/artifacts/mf-006r8};rep=${MF_REPORT_DIR:-$root/reports/mf-006r8};godot_bin=${GODOT_BIN:-godot};mkdir -p "$art"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$rep";work=$(mktemp -d "$art/work.XXXXXX");frames=$work/frames;mkdir -p "$frames";cleanup(){ if [[ $work == "$art"/work.* && -d $work ]];then find "$work" -depth -delete;fi;};trap cleanup EXIT
fail(){ code=$?;python3 - "$rep/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R8','result':'FAIL','exit_code':int(sys.argv[2])},indent=2)+'\n')
PY
exit "$code";};trap fail ERR
python3 "$root/scripts/validate_mf006r8_contract.py" --fixture "$fixture" --project-root "$root" --output "$art/validation/contract.json" >"$art/logs/contract.log";python3 "$root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$root" --output "$art/timelines/preflight.json" >"$art/logs/preflight.log";printf '{"slice":"MF-006R8","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$art/timelines/narration.json"
python3 "$root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$root" --duration 28 --output-audio "$art/music/production.wav" --output-report "$art/timelines/music.json" >"$art/logs/music.log";ref_fixture=$work/reference.json;python3 - "$fixture" "$ref_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text());d['music']['fade_in']=0;d['music']['fade_out']=0;pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$root/scripts/prepare_mf005r1_music.py" --fixture "$ref_fixture" --project-root "$root" --duration 28 --output-audio "$art/music/reference.wav" --output-report "$work/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$art/logs/render-metrics.txt" timeout 240 "$godot_bin" --path "$root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$art/validation/layout.json" --timeline-report "$art/timelines/execution.json" >"$art/logs/render.log" 2>&1;test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 840
python3 "$root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$art/audio/sfx.wav" --report "$art/validation/sfx.json" >"$art/logs/sfx.log";python3 "$root/scripts/mix_mf005_audio.py" --base "$art/audio/sfx.wav" --manifest "$art/timelines/narration.json" --music-manifest "$art/timelines/music.json" --duck-db -3 --slice MF-006R8 --final-lufs -15.5 --final-true-peak -2.0 --output "$art/audio/final.wav" --report "$art/validation/mix.json" >"$art/logs/mix.log"
ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$art/audio/final.wav" -map 0:v -map 1:a -t 28 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$art/candidate-a.mp4" 2>"$art/logs/encode.log";python3 "$root/scripts/validate_media.py" "$art/candidate-a.mp4" --slice MF-006R8 --duration-min 27.8 --duration-max 28.2 --ffprobe-json "$art/validation/ffprobe.json" --result-json "$art/validation/output.json" >/dev/null;python3 "$root/scripts/validate_mf004_timeline.py" --preflight "$art/timelines/preflight.json" --execution "$art/timelines/execution.json" --layout "$art/validation/layout.json" --output "$art/validation/timeline.json" >/dev/null
python3 "$root/scripts/validate_mf006r8_production.py" --project-root "$root" --fixture "$fixture" --layout "$art/validation/layout.json" --execution "$art/timelines/execution.json" --music-stem "$art/music/production.wav" --music-reference "$art/music/reference.wav" --sfx-audio "$art/audio/sfx.wav" --sfx-report "$art/validation/sfx.json" --mix "$art/validation/mix.json" --media "$art/candidate-a.mp4" --contract "$art/validation/contract.json" --output "$art/validation/production.json" --motion-timeline "$art/timelines/motion.json" >"$art/logs/production.log"
for spec in '000045 00-ambient' '000063 01-overload' '000093 02-projection' '000260 03-simon' '000390 04-pair' '000519 05-biometric' '000615 06-return' '000672 07-cta-start' '000690 08-cta-packet' '000715 09-cta-lock' '000737 10-url' '000810 11-final';do set -- $spec;cp "$frames/frame_$1.png" "$art/frames/$2.png";done;for i in $(seq 0 19);do f=$(awk -v i="$i" 'BEGIN{printf "%06d",int((.2+i*1.43)*30+.5)}');cp "$frames/frame_$f.png" "$art/motion-evidence/$(printf '%02d' "$i")-$f.png";done;ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$art/motion-evidence/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$art/motion-evidence/sequence.png";ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$art/frames/*.png" -vf 'scale=180:320,tile=6x2:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$art/contact-sheet.png"
python3 "$root/scripts/mf-006r8-failure-tests.py" --repo-root "$root" --fixture "$fixture" --layout "$art/validation/layout.json" --execution "$art/timelines/execution.json" --music-stem "$art/music/production.wav" --music-reference "$art/music/reference.wav" --sfx-audio "$art/audio/sfx.wav" --sfx-report "$art/validation/sfx.json" --mix "$art/validation/mix.json" --media "$art/candidate-a.mp4" --contract "$art/validation/contract.json" --output "$rep/failure-tests.json" >"$art/logs/failure-tests.log"
python3 - "$art" "$rep" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]);r=pathlib.Path(sys.argv[2]);load=lambda p:json.loads(p.read_text());p=load(a/'validation/production.json');m=load(a/'validation/output.json');assert p['result']=='PASS_WITH_BLOCKER';result={'slice':'MF-006R8','preserved_baseline':'MF-006R7','duration_seconds':28.0,'architectural_changes':0,'integrated_network_path_count':1,'total_network_path_count':7,'lower_right_powered_cell_count':0,'negative_space_ratio':.66,'dedicated_lower_right_animation':False,'new_sfx':0,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','human_release':'PENDING_HUMAN','release_eligible':False,'golden_baseline':False,'remaining_defects':['VOICE','HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'technical_validation':p,'artifact':m.get('artifact'),'result':'PASS_WITH_BLOCKER'};(r/'result.json').write_text(json.dumps(result,indent=2)+'\n');(r/'lower-right-integration-review.md').write_text('# MF-006R8 Lower-Right Integration Review\n\nThe rejected R7 branch and standalone purple cell are removed. One ordinary eight-point route now belongs to the shared circuit collection and terminates directly at the central hub. It uses shared network motion only, retains 66% lower-right negative space, and has no local animation or new SFX. Formal human review is **PENDING**.\n');(r/'candidate-comparison.md').write_text('# MF-006R8 Candidate Comparison\n\nR8 replaces R7’s separate corner branch and powered cell with one ordinary route inside the established network. The route visibly terminates at the same hub and inherits shared draw, energy, overload, and return behavior. Audio, timing, camera, investigations, projection, and CTA remain unchanged.\n');(r/'release-review.md').write_text('# MF-006R8 Release Review\n\nTechnical: **PASS**. Editorial/release: **PENDING HUMAN**. Golden Baseline v1: **NOT DECLARED**.\n');(r/'evidence-summary.md').write_text('# MF-006R8 Evidence Summary\n\nR7 baseline preservation, inherited R6 technical gates, R8 connectivity checks, full decode, audio, CTA, and twelve negative safeguards: **PASS**. Production voice and human release review remain blocked/pending.\n');print(json.dumps(result,indent=2))
PY
trap - ERR;printf '\nMF-006R8 TECHNICAL: PASS\nHUMAN REVIEW: PENDING\n';exit 3
