#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); export PATH="${HOME}/.local/bin:${PATH}"; godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006r3-unknown-process.json; grammar=$repo_root/config/visual-grammar.json; artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r3}; report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r3}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir"; work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX"); frames=$work_dir/frames; mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]]; then find "$work_dir" -depth -delete; fi; }; trap cleanup EXIT
fail_result(){ code=$?; python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R3','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R3 EXECUTION FAILED\n' >&2; exit "$code"; }; trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006R3\n========================\n\nCONTRACT\n'
python3 "$repo_root/scripts/validate_mf006r3_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006R3","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"
printf '[PASS] approved copy, one-window-only center, destination, music\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'

python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json; python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text()); d['music']['fade_in']=0; d['music']['fade_out']=0; pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 180 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 549
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R3 --final-lufs -16 --final-true-peak -2.0 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 18.3 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R3 --duration-min 18.1 --duration-max 18.5 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r3_production.py" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"

for specification in '000000 00-path-start' '000015 01-path-draw' '000036 02-charge' '000046 03-overload' '000054 04-burst' '000075 05-window-title' '000126 06-type-start' '000150 07-hunted-hold' '000195 08-targets-start' '000225 09-targets-hold' '000270 10-biometrics-start' '000305 11-biometrics-hold' '000360 12-collapse' '000390 13-reclaimed' '000465 14-cta-start' '000525 15-cta-hold'; do set -- $specification; cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png"; done
for index in $(seq 0 19); do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*.91)*30+.5)}'); cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png"; done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=8x2:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r3-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]); r=pathlib.Path(sys.argv[2]); load=lambda p:json.loads(p.read_text()); production=load(a/'validation/production.json'); contract=load(a/'validation/contract.json'); media=load(a/'validation/output.json'); sfx=load(a/'validation/sfx.json'); assert production['result']=='PASS_WITH_BLOCKER' and production['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS'
result={'slice':'MF-006R3','selected_book':{'title':'Unknown Process','canonical_author':'Robert C. Blanzy','display_author':'R.C. Blanzy','series':'The Second Presence','book_number':1},'center_concept':'single persistent projected recovered-record window','primary_window_count':1,'split_book_used':False,'wavy_center_line':False,'yellow_circular_graphic':False,'story_text_inside_window':True,'typed_text':True,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','release_eligible':False,'blockers':contract['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'duration_seconds':18.3,'background_cells':{'dark':42,'purple':3,'green':3,'blue':3,'cyan':3},'depth_layers':4,'renderer_implementation_files_changed':3,'renderer_architecture_changes':0,'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'}; (r/'result.json').write_text(json.dumps(result,indent=2)+'\n')
(r/'projection-layout.md').write_text('''# MF-006R3 Projection Layout\n\nOne persistent mildly tilted window occupies a 416×350 region with a documented 338×239 internal content safe area. All three measured story-text rectangles are contained by that safe area. A dark translucent backing suppresses circuits and wall colors beneath content. The node sits below the content, and the screen persists while typed record content refreshes in place. No split planes, page turns, or alternate screen instances exist.\n''')
(r/'background-cell-treatment.md').write_text('''# MF-006R3 Background Cell Treatment\n\nSeed `26063` deterministically selects 12 of 54 wall cells: three purple, three green, three blue, and three cyan. Forty-two dark/current cells remain the majority. Accent opacity is materially higher than R2, while cells behind the reading area are dimmed to 48%. Pulses are slow, unsynchronized, and respond slightly to overload/CTA events.\n''')
(r/'candidate-comparison.md').write_text('''# MF-006R3 Candidate Comparison\n\n| Dimension | R2 | R3 candidate A |\n|---|---|---|\n| Center | paired codex planes | one persistent recovered-record window |\n| Content | phrases near/across split geometry | left-aligned typed phrases inside measured safe area |\n| Transitions | projection-plane state changes | same screen, interference wipe, clear, type-on |\n| Center clutter | middle wavy cable and large biometric rings | center cable removed; minimal non-circular biometric bars |\n| Wall color | subtle 18.5% accents | visible bounded 22.2% seeded accents |\n| Hierarchy | node/lines compete with content | dark screen backing; node below and subordinate |\n| Audio | 12 projection cues | 10 meaningful cues; no character beeps |\n\nOnly candidate A was produced because it directly resolves the specified hierarchy defects. A glitchier variant would risk reintroducing clutter before human review.\n''')
(r/'editorial-review.md').write_text('''# MF-006R3 Editorial Review\n\n## Agent pre-review\n\nThe evidence shows one coherent screen, text contained inside it, type-on behavior, distinct in-screen motifs, no split-book silhouette, no center wavy cable, no yellow circular graphic, and immediately stronger purple/green/blue wall cells. The middle is cleaner and reads more like a recovered sci-fi record than a sequence of slides.\n\n## Required human review\n\n**PENDING.** Review the 25 R3 questions against `artifacts/mf-006r3/candidate-a.mp4`. In particular verify phone-size phrase/URL comfort and answer both: “Does the text belong to the screen?” and “Are purple, green, and blue cells immediately noticeable without distracting?” This report does not impersonate human approval.\n''')
(r/'evidence-summary.md').write_text('''# MF-006R3 Evidence Summary\n\nVisual/audio technical subgate: **PASS**. Fifteen negative safeguards: **PASS**. Production voice: **BLOCKED**. Human editorial: **PENDING**. Release: **NO**.\n\nR3 establishes one persistent recovered-record window with typed safe-area text, removes the split book, center cable, and large yellow rings, increases bounded wall-cell color visibility, preserves causal circuitry, collapses the screen into the node, and machine-builds the CTA. Continuous approved music, measured fades, final loudness, 10 restrained SFX, full decode, and timeline execution validate.\n\nRecommended next step: human hierarchy/readability review, then production voice. If still below release quality, refine font hierarchy and screen contrast—not the core single-window metaphor.\n''')
print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006R3 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL: PENDING\nRELEASE_ELIGIBLE: NO\n'
exit 3
