#!/usr/bin/env bash
set -Eeuo pipefail
repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd);export PATH="${HOME}/.local/bin:${PATH}";godot_bin=${GODOT_BIN:-godot};fixture=$repo_root/content/fixtures/mf006r6-unknown-process.json;grammar=$repo_root/config/visual-grammar.json;artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r6};report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r6}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir";work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX");frames=$work_dir/frames;mkdir -p "$frames";cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]];then find "$work_dir" -depth -delete;fi;};trap cleanup EXIT
fail_result(){ code=$?;python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R6','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','human_release':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R6 EXECUTION FAILED\n' >&2;exit "$code";};trap fail_result ERR
printf 'MEDIA FOUNDRY — MF-006R6\n========================\n\nCONTRACT\n';python3 "$repo_root/scripts/validate_mf006r6_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log";python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log";printf '{"slice":"MF-006R6","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json";printf '[PASS] R5 baseline lock, final-polish contract, unchanged architecture\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log";reference_fixture=$work_dir/reference.json;python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text());d['music']['fade_in']=0;d['music']['fade_out']=0;pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 240 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1;test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 840
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log";python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R6 --final-lufs -15.5 --final-true-peak -2.0 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 28 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R6 --duration-min 27.8 --duration-max 28.2 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null;python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r6_production.py" --project-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"
for specification in '000000 00-paths' '000057 01-overload-start' '000063 02-pulse-one' '000072 03-pulse-two' '000077 04-overload-peak' '000087 05-projection' '000234 06-simon-search' '000260 07-simon-lock' '000273 08-simon-hold' '000291 09-reset-one' '000354 10-bridge-travel' '000390 11-bridge-lock' '000401 12-bridge-hold' '000419 13-reset-two' '000483 14-biometric-scan' '000519 15-hidden-lock' '000533 16-biometric-hold' '000573 17-collapse' '000615 18-return' '000676 19-cta-packets' '000696 20-cta-assembly' '000715 21-cta-lock' '000737 22-url-stable' '000810 23-final-frame';do set -- $specification;cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png";done
for index in $(seq 0 23);do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*1.17)*30+.5)}');cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png";done;ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=6x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png";ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=6x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r6-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"
python3 - "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]);r=pathlib.Path(sys.argv[2]);load=lambda p:json.loads(p.read_text());p=load(a/'validation/production.json');c=load(a/'validation/contract.json');media=load(a/'validation/output.json');sfx=load(a/'validation/sfx.json');assert p['result']=='PASS_WITH_BLOCKER' and p['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS';result={'slice':'MF-006R6','preserved_baseline':'MF-006R5','duration_seconds':28.0,'architectural_changes':0,'new_visual_metaphors':0,'investigation_motion_polished':True,'overload_pulse_events':2,'breathing_cells':6,'projection_physicality':True,'record_completion_holds':3,'record_reset_events':2,'cta_energy_packet_paths':2,'event_specific_sfx':6,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','narration_alignment':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','human_release':'PENDING_HUMAN','release_eligible':False,'golden_baseline':False,'blockers':c['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'failure_tests':'PASS','technical_validation':p,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'};(r/'result.json').write_text(json.dumps(result,indent=2)+'\n');(a/'validation/preservation.json').write_text(json.dumps({'slice':'MF-006R6','entries':p['preservation'],'result':'PASS'},indent=2)+'\n')
(r/'motion-review.md').write_text('''# MF-006R6 Motion Review\n\nSimon gains a visible completion ring and locked center after acquisition. Three packets visibly travel across the Leo/Zeph bridge before stable confirmation. The biometric scan traverses the compact trace and isolates one illuminated hidden segment. Three result holds and two reset/refresh states preserve the same projection surface.\n''');(r/'audio-review.md').write_text('''# MF-006R6 Audio Review\n\nThirteen foreground cues map to visible events. The shared family now differentiates target acquisition, dual-node bridge lock, hidden-data reveal, two record refreshes, overload rise, projection formation, collapse/return, and CTA resolve. Music source, gain direction, 1.4/2.2-second fades, and final loudness architecture remain unchanged. Production narration and CTA narration sync remain blocked because no approved production voice exists.\n''');(r/'final-polish-review.md').write_text('''# MF-006R6 Final Polish Review\n\nAgent frame review must confirm clearer investigation endpoints, restrained six-cell breathing, stable readable text with edge-only shimmer, explicit completion/reset rhythm, visible orange CTA packets, and a clean final hold. Formal human editorial review remains **PENDING** and is not impersonated here.\n''');(r/'release-review.md').write_text('''# MF-006R6 Release Review\n\nTechnical: **PASS**. Editorial: **PENDING HUMAN**. Release: **NO**. Golden Baseline v1: **NOT DECLARED**.\n\nBlocking classifications: `VOICE`, plus required human editorial and release judgment. If visual review identifies a defect, classify it narrowly; do not redesign the format.\n''');(r/'evidence-summary.md').write_text('''# MF-006R6 Evidence Summary\n\nFinal visual/audio technical polish: **PASS**. Twenty-one negative safeguards: **PASS**. R5 baseline preservation: **PASS**. Production voice and narration alignment: **BLOCKED**. Human editorial/release: **PENDING**. Golden baseline: **NO**.\n''');print(json.dumps(result,indent=2))
PY
trap - ERR;printf '\nMF-006R6 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL/RELEASE: PENDING\nGOLDEN BASELINE: NO\n';exit 3
