#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); export PATH="${HOME}/.local/bin:${PATH}"; godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006-dark-signal.json; grammar=$repo_root/config/visual-grammar.json; artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006}; report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation,voice-auditions} "$report_dir"; work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX"); frames=$work_dir/frames; mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]]; then find "$work_dir" -depth -delete; fi; }; trap cleanup EXIT
fail_result(){ local code=$?; python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006','gates':{'visual_audio_technical':'FAIL','technical':'FAIL','editorial':'BLOCKED','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2])},indent=2)+'\n')
PY
printf '\nMF-006 EXECUTION FAILED\n' >&2; exit "$code"; }; trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006\n======================\n\nBASELINE\n'
python3 - "$repo_root" "$artifact_dir/validation/regression-before.json" <<'PY'
import json,pathlib,sys
root=pathlib.Path(sys.argv[1]); names=['mf-001','mf-002','mf-002r1','mf-003','mf-004','mf-005','mf-005r1','mf-005r2','mf-005r3','mf-pilot-001']; gates={}
for name in names:
 data=json.loads((root/'reports'/name/'result.json').read_text()); passed=data.get('result')=='PASS' or data.get('technical_result')=='PASS' or data.get('gates',{}).get('technical')=='PASS'; assert passed; gates[name]='PASS'
r4=json.loads((root/'reports/mf-005r4/result.json').read_text()); assert r4.get('visual_audio_technical')=='PASS'; gates['mf-005r4_visual_audio']='PASS'
pathlib.Path(sys.argv[2]).write_text(json.dumps({'slice':'MF-006','gates':gates,'result':'PASS'},indent=2)+'\n')
PY
jq -r '.gates|to_entries[]|"[PASS] \(.key)"' "$artifact_dir/validation/regression-before.json"

source_music=$repo_root/media/audio/music/waiting-for-the-shift.mp3; test -s "$source_music"; expected_hash=$(jq -r '.music.provenance.sha256' "$fixture"); test "$(sha256sum "$source_music"|awk '{print $1}')" = "$expected_hash"
python3 "$repo_root/scripts/inspect_audio_asset.py" --input "$source_music" --output "$artifact_dir/validation/music-source.json" >"$artifact_dir/logs/music-source.log"
python3 "$repo_root/scripts/validate_mf006_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"
python3 "$repo_root/scripts/validate_mf006_narration.py" --fixture "$fixture" --manifest "$artifact_dir/timelines/narration.json" --output "$artifact_dir/validation/narration.json" >"$artifact_dir/logs/narration.log"
printf '[PASS] approved Dark Signal metadata and supplied music\n[BLOCKED] approved website and production voice unavailable\n\nPRODUCTION\n'

python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 19.8 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json; python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text()); d['music']['fade_in']=0; d['music']['fade_out']=0; pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 19.8 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 180 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 594
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/mix-metrics.txt" python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006 --final-lufs -16 --final-true-peak -1.5 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 19.8 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/book-promo.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/book-promo.mp4" --slice MF-006 --duration-min 19.6 --duration-max 20.0 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006_production.py" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --narration "$artifact_dir/validation/narration.json" --music "$artifact_dir/timelines/music.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/book-promo.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"
printf '[PASS] generated chamber/book/events, low-res upscale, music fades, SFX, mix, output\n'

for specification in '000000 00-00.00-circuits' '000045 01-01.50-convergence' '000075 02-02.50-formation' '000120 03-04.00-open' '000153 04-05.10-page1' '000228 05-07.60-page2' '000303 06-10.10-page3' '000375 07-12.50-close' '000435 08-14.50-dissolve' '000525 09-17.50-cta'; do set -- $specification; cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png"; done
for index in $(seq 0 19); do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.3+i*.95)*30+.5)}'); cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png"; done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=5x2:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
ffmpeg -hide_banner -loglevel error -y -i "$artifact_dir/music/production.wav" -filter_complex 'showwavespic=s=1000x180:colors=0x39b8c9' -frames:v 1 "$artifact_dir/music/waveform.png"
ffmpeg -hide_banner -loglevel error -y -i "$artifact_dir/audio/final.wav" -filter_complex 'showwavespic=s=1000x220:colors=0xe55b2c' -frames:v 1 "$artifact_dir/audio/waveform.png"
python3 "$repo_root/scripts/mf-006-failure-tests.py" --repo-root "$repo_root" --artifacts "$artifact_dir" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]); r=pathlib.Path(sys.argv[2]); load=lambda p:json.loads(p.read_text()); production=load(a/'validation/production.json'); output=load(a/'validation/output.json'); contract=load(a/'validation/contract.json'); music=load(a/'timelines/music.json'); sfx=load(a/'validation/sfx.json'); assert production['result']=='PASS_WITH_BLOCKERS' and production['gates']['visual_audio_technical']=='PASS' and output['result']=='PASS'
result={'slice':'MF-006','selected_book':{'title':'Dark Signal','author':'R.C. Blanzy','series':'The Second Presence Trilogy','book_number':2},'visual_audio_technical':'PASS','gates':production['gates'],'candidate_valid':False,'release_eligible':False,'blockers':contract['blockers'],'duration_seconds':19.8,'internal_resolution':'540x960','output_resolution':'1080x1920','upscale':'nearest-neighbor','static_book_cover_used':False,'voice_auditions':0,'website':None,'music':{'source':'Waiting_for_the_Shift.mp3','sha256':music['source_sha256'],'offset':music['selected_offset'],'fade_in':music['fade_in'],'fade_out':music['fade_out'],'gain_db':music['gain_db']},'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':output.get('artifact'),'remaining_defects':['APPROVED_WEBSITE','PRODUCTION_VOICE','HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW']}; (r/'result.json').write_text(json.dumps(result,indent=2)+'\n')
(r/'visual-direction.md').write_text('''# MF-006 Visual Direction\n\n**Strategy:** Godot-generated low-resolution science-fiction chamber. The approved Dark Signal cover was inspected only for dark blue/cyan/orange atmosphere and title hierarchy; no cover pixels, texture, screenshot, or external artwork are loaded by the fixture or renderer.\n\nThe 540×960 scene contains battered panels, hanging cables, crude LEDs, moving circuit paths, an electronic platform, burst particles, a generated cover/spine/page block, three independent page states, camera reactions, data fragments, and an in-world CTA. It is upscaled to 1080×1920 with nearest-neighbor sampling.\n''')
(r/'production-contract.md').write_text('''# MF-006 Production Contract\n\nSelected approved metadata: **Dark Signal**, Book Two of **The Second Presence Trilogy**, by **R.C. Blanzy**. Approved copy is limited to “The strangest AI conversations aren’t happening in labs. They’re happening in fiction.”\n\nNo approved concise website and no production-eligible narration provider were found. Neither was fabricated. Flite is prohibited and absent. The generated-world/music/SFX candidate is reviewable, but Technical and Release remain blocked.\n''')
(r/'editorial-timeline.md').write_text('''# MF-006 Editorial Timeline\n\n| Time | Generated action | Audio |\n|---:|---|---|\n| 0.0–1.8 | circuits crawl and converge | music emerges; electrical motion |\n| 1.8–3.4 | controlled spark; title gains backing; book forms | spark and formation |\n| 3.4–4.6 | camera pushes; generated cover opens | physical open |\n| 4.6–7.0 | page 1: STRANGEST AI CONVERSATIONS | page flip; narration blocked |\n| 7.0–9.5 | page 2: NOT HAPPENING IN LABS | page flip; narration blocked |\n| 9.5–12.0 | page 3: HAPPENING IN FICTION | page flip; narration blocked |\n| 12.0–13.2 | book closes | physical close |\n| 13.2–16.4 | book deconstructs into circuit fragments | data dissolution |\n| 16.4–19.8 | CONTINUE THE ADVENTURE forms in-world | music resolves/fades; final voice blocked |\n''')
(r/'audio-review.md').write_text(f'''# MF-006 Audio Review\n\nUser-supplied `Waiting_for_the_Shift.mp3` is preserved byte-for-byte at SHA-256 `{music['source_sha256']}`. The production uses the natural 0-second opening, {music['gain_db']} dB gain, a measured {music['fade_in']}s entrance, and {music['fade_out']}s exit. Nine deterministic SFX correspond to circuits, spark, formation, open, three page turns, close, and dissolution.\n\nNo narration is present. Music ducking configuration is preserved for later approved speech, but cannot be auditioned until a production voice or user recording is supplied.\n''')
(r/'evidence-summary.md').write_text('''# MF-006 Evidence Summary\n\nGenerated-world visual/audio subgate: **PASS**. Technical: **FAIL**. Editorial: **BLOCKED_APPROVED_INPUTS**. Release: **RELEASE_ELIGIBLE_NO**.\n\nThe candidate is a continuous 19.8-second Godot-native miniature scene rendered at 540×960 and deterministically upscaled. Nineteen events, ten components, five camera/reaction events, three pages, measured music fades, nine physical SFX, safe CTA text, 1080×1920 output, and full decode validate. No static book cover is embedded.\n\nThe approved website and production voice are unavailable. Consequently no URL is displayed, no narration is synthesized, and the mandatory spoken final CTA is absent. Human editorial/release review cannot complete until those inputs are supplied.\n\n- Video: `artifacts/mf-006/book-promo.mp4`\n- Motion: `artifacts/mf-006/motion-evidence/sequence.png`\n- Contact sheet: `artifacts/mf-006/contact-sheet.png`\n- Validation: `artifacts/mf-006/validation/production.json`\n''')
print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006 GENERATED-WORLD/AUDIO SUBGATE: PASS\nMF-006 TECHNICAL: FAIL — APPROVED WEBSITE + PRODUCTION VOICE REQUIRED\nEDITORIAL: BLOCKED_APPROVED_INPUTS\nRELEASE_ELIGIBLE: NO\n'
exit 3
