#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd);export PATH="${HOME}/.local/bin:${PATH}";godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006r5-unknown-process.json;grammar=$repo_root/config/visual-grammar.json;artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r5};report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r5}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir";work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX");frames=$work_dir/frames;mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]];then find "$work_dir" -depth -delete;fi;};trap cleanup EXIT
fail_result(){ code=$?;python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R5','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R5 EXECUTION FAILED\n' >&2;exit "$code";};trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006R5\n========================\n\nCONTRACT\n'
python3 "$repo_root/scripts/validate_mf006r5_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006R5","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"
printf '[PASS] approved copy, R4 baseline lock, one-window live-investigation contract\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'

python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json;python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text());d['music']['fade_in']=0;d['music']['fade_out']=0;pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 240 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 840
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R5 --final-lufs -15.5 --final-true-peak -2.0 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 28 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R5 --duration-min 27.8 --duration-max 28.2 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r5_production.py" --project-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"

for specification in '000000 00-path-start' '000057 01-overload-start' '000069 02-overload-peak' '000081 03-burst' '000186 04-simon-query' '000234 05-simon-trace' '000260 06-simon-confirm' '000300 07-pair-query' '000354 08-pair-discovery' '000390 09-pair-confirm' '000428 10-biometric-query' '000483 11-biometric-scan' '000519 12-hidden-confirm' '000573 13-collapse' '000615 14-energy-return' '000672 15-cta-energy' '000687 16-cta-typing' '000715 17-cta-lock' '000735 18-url-stable' '000810 19-final-resolve';do set -- $specification;cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png";done
for index in $(seq 0 23);do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*1.17)*30+.5)}');cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png";done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=6x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r5-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]);r=pathlib.Path(sys.argv[2]);load=lambda p:json.loads(p.read_text());production=load(a/'validation/production.json');contract=load(a/'validation/contract.json');media=load(a/'validation/output.json');sfx=load(a/'validation/sfx.json');assert production['result']=='PASS_WITH_BLOCKER' and production['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS'
result={'slice':'MF-006R5','selected_book':{'title':'Unknown Process','canonical_author':'Robert C. Blanzy','display_author':'R.C. Blanzy','series':'The Second Presence','book_number':1},'preserved_baseline':'MF-006R4','center_concept':'single persistent projected live-investigation window','primary_window_count':1,'live_investigations':3,'query_events':3,'confirmation_events':3,'overload_duration_seconds':.8,'overload_added_emphasis_seconds':.5,'green_cell_emphasis':.31,'cta_system_lock':True,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','release_eligible':False,'blockers':contract['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'duration_seconds':28.0,'renderer_architecture_changes':0,'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'};(r/'result.json').write_text(json.dumps(result,indent=2)+'\n');(a/'validation/preservation.json').write_text(json.dumps({'slice':'MF-006R5','entries':production['preservation'],'result':'PASS'},indent=2)+'\n')
(r/'candidate-comparison.md').write_text('''# MF-006R5 Candidate Comparison\n\n| Dimension | R4 baseline | R5 candidate A |\n|---|---|---|\n| Record behavior | type, activity, signal lock | query fragments, scan/search, staged evidence, confirmation, evidence lock |\n| Simon | tracking motif | moving acquisition box and confirmed subject trace |\n| Leo / Zeph | linked-node motif | nodes resolve sequentially before their bridge stabilizes |\n| Biometrics | moving scan | incomplete trace reveals two hidden warning segments |\n| Overload | 0.3 s | 0.8 s with denser packets, tighter rings, brighter peak, wall reaction |\n| Green cells | visible minority | explicitly boosted and event-reactive while remaining subordinate |\n| CTA | typed reveal | final transmission, typed result, signal lock, stabilized URL |\n\nOne candidate was produced because the requested direction is narrow and does not present a meaningful alternate grammar.\n''')
(r/'live-investigation-review.md').write_text('''# MF-006R5 Live Investigation Review\n\n## Agent pre-review\n\nThe evidence shows all three records beginning with incomplete query fragments and a moving scan before the phrase completes. Simon acquires a moving target, Leo and Zeph resolve independently before a pulsing bridge connects them, and the biometric trace exposes highlighted hidden segments. Each state confirms and locks before refresh. The window remains a single persistent instance.\n\n## Required human review\n\n**PENDING.** The core question remains: “Do the projected records now behave like live investigations rather than formatted information cards?” Review all 19 brief questions against `artifacts/mf-006r5/candidate-a.mp4`. This report does not impersonate human approval.\n''')
(r/'node-overload-notes.md').write_text('''# MF-006R5 Node Overload Notes\n\nThe overload-to-burst interval increases from 0.3 to 0.8 seconds, adding 0.5 seconds within the requested range. Four faster packets per path converge during anticipation, the node gains a brighter inner pulse and four tightening rings, green cells brighten, and three restrained environment ripples respond. Projection still follows the burst and the full opening remains compact.\n''')
(r/'color-cell-notes.md').write_text('''# MF-006R5 Color Cell Notes\n\nThe seeded 12-of-54 accent ratio remains unchanged: three purple, three green, three blue, and three cyan cells against 42 dark cells. R5 selectively overlays the three green cells at a measured 0.31 emphasis and adds bounded reactions during overload and record initialization. Central cells remain dimmed to protect reading hierarchy.\n''')
(r/'evidence-summary.md').write_text('''# MF-006R5 Evidence Summary\n\nVisual/audio technical subgate: **PASS**. Twenty negative safeguards: **PASS**. Production voice: **BLOCKED**. Human editorial: **PENDING**. Release: **NO**.\n\nR5 preserves R4 and the single-window architecture while turning three formatted record states into staged investigations. It strengthens overload anticipation, selectively improves green infrastructure visibility, and makes the CTA the system’s final locked transmission. The 28-second cut, approved music fades, 12 purposeful SFX, loudness/peak, event execution, safe areas, baseline hashes, and full decode validate.\n''');print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006R5 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL: PENDING\nRELEASE_ELIGIBLE: NO\n';exit 3
