#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); export PATH="${HOME}/.local/bin:${PATH}"; godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006r1-unknown-process.json; grammar=$repo_root/config/visual-grammar.json; artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r1}; report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r1}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir"; work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX"); frames=$work_dir/frames; mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]]; then find "$work_dir" -depth -delete; fi; }; trap cleanup EXIT
fail_result(){ code=$?; python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R1','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R1 EXECUTION FAILED\n' >&2; exit "$code"; }; trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006R1\n========================\n\nCONTRACT\n'
python3 "$repo_root/scripts/validate_mf006r1_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006R1","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"

printf '[PASS] Unknown Process approved copy, metadata, destination, generated-only strategy, music\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json; python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text()); d['music']['fade_in']=0; d['music']['fade_out']=0; pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 180 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 549
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R1 --final-lufs -16 --final-true-peak -1.5 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 18.3 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R1 --duration-min 18.1 --duration-max 18.5 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r1_production.py" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"

for specification in '000000 00-paths-start' '000015 01-paths-drawn' '000036 02-node-charge' '000046 03-overload' '000054 04-burst' '000081 05-book' '000132 06-hunted' '000210 07-targets' '000285 08-biometric' '000375 09-dissolve' '000465 10-cta' '000525 11-cta-hold'; do set -- $specification; cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png"; done
for index in $(seq 0 19); do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*.91)*30+.5)}'); cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png"; done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=4x3:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r1-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$repo_root" "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
root=pathlib.Path(sys.argv[1]); a=pathlib.Path(sys.argv[2]); r=pathlib.Path(sys.argv[3]); load=lambda p:json.loads(p.read_text()); production=load(a/'validation/production.json'); contract=load(a/'validation/contract.json'); media=load(a/'validation/output.json'); sfx=load(a/'validation/sfx.json'); assert production['result']=='PASS_WITH_BLOCKER' and production['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS'
result={'slice':'MF-006R1','selected_book':{'title':'Unknown Process','canonical_author':'Robert C. Blanzy','display_author':'R.C. Blanzy','series':'The Second Presence','book_number':1},'subject_switch':'PASS','approved_source':contract['approved_source'],'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','release_eligible':False,'blockers':contract['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'duration_seconds':18.3,'internal_resolution':'540x960','output_resolution':'1080x1920','static_book_cover_used':False,'renderer_implementation_files_changed':3,'renderer_architecture_changes':0,'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'}; (r/'result.json').write_text(json.dumps(result,indent=2)+'\n')
(r/'visual-causality-notes.md').write_text('''# MF-006R1 Visual Causality Notes\n\nSix right-angle paths draw before twelve packets travel along those exact polylines into one central node. Charge rings expand, overload precedes the burst, and the burst assembles the title/book. The close dissolves the book back into packets that reverse along the same paths. CTA wiring is energized before the destination appears.\n\nThe former trapezoid is removed. Its replacement is a documented book-generation cradle with two rails, four clamps, six contacts, and an induction coil.\n''')
(r/'candidate-comparison.md').write_text('''# MF-006R1 Candidate Comparison\n\n| Dimension | Before: MF-006 technical proof | After: MF-006R1 candidate A |\n|---|---|---|\n| Subject | Dark Signal placeholder | Unknown Process, approved Book One copy |\n| Circuits | decorative/free-floating pulses | paths draw first; packets sample exact path geometry |\n| Center | generic convergence/burst | charge rings → overload → earned burst |\n| Book | flat rectangular page object | perspective covers, spine, page block, edges, hinges, shadow |\n| Pages | text swaps | reticle/hunt, dual-node bridge, biometric lock |\n| Support | ambiguous trapezoid platform | purposeful mechanical generation cradle |\n| Ending | boxed CTA panel | return energy and wired in-world CTA/URL |\n| Audio | 9 generic physical cues | 12 cues including path draw, flow, overload, and CTA energy |\n\nCandidate A is the single controlled refinement selected; additional variants would add render cost before human review identifies a meaningful axis.\n''')
(r/'editorial-review.md').write_text('''# MF-006R1 Editorial Review\n\n## Agent pre-review\n\nThe evidence shows the requested causal sequence, three distinct page treatments, physical book depth cues, purposeful cradle, opening/closing symmetry, integrated CTA, and readable destination. The direction should be kept and refined rather than abandoned.\n\n## Human review\n\n**PENDING.** A human must review `artifacts/mf-006r1/candidate-a.mp4` against the 18 questions in the MF-006R1 brief. This report does not impersonate that decision. Particular judgment points are whether the page perspective reads as sufficiently physical at phone size and whether the 2.8-second URL hold is comfortable.\n''')
(r/'evidence-summary.md').write_text('''# MF-006R1 Evidence Summary\n\nVisual/audio technical subgate: **PASS**. Nine negative safeguards: **PASS**. Production voice: **BLOCKED**. Human editorial: **PENDING**. Release: **NO**.\n\nThe 18.3-second candidate is a continuous Godot-native scene rendered at 540×960 and deterministically upscaled to 1080×1920. It contains six causal circuit paths, node buildup/overload/burst, a generated physical book with three differentiated story pages, a purposeful cradle, return-path dissolution, integrated canonical URL, continuous user-approved music with measured fades, and 12 synchronized SFX. No cover image or external visual is loaded.\n\nBefore/after evidence: `reports/mf-006r1/candidate-comparison.md`; contact sheet: `artifacts/mf-006r1/contact-sheet.png`; motion sequence: `artifacts/mf-006r1/motion-evidence/sequence.png`; validation: `artifacts/mf-006r1/validation/production.json`.\n\nRemaining blockers are a production-eligible performance of the approved narration/final CTA and human editorial/release decisions. Recommended next refinement: obtain the voice, then tune page perspective and URL hold only if human review flags them.\n''')
print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006R1 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL: PENDING\nRELEASE_ELIGIBLE: NO\n'
exit 3
