#!/usr/bin/env python3
"""Prove MF-006R6 rejects final-polish regressions."""
import argparse,copy,json,subprocess,tempfile
from pathlib import Path
def main():
 p=argparse.ArgumentParser()
 for n in ('repo_root','fixture','layout','execution','music_stem','music_reference','sfx_audio','sfx_report','mix','media','contract','output'):p.add_argument('--'+n.replace('_','-'),required=True)
 a=p.parse_args();base=json.loads(Path(a.layout).read_text());cases=[];m={
 'two_windows':lambda d:d['generated_scene']['projected_data_window'].update(primary_window_count=2),'split_returns':lambda d:d['generated_scene']['projected_data_window'].update(split_page_projection=True),'wavy_returns':lambda d:d['generated_scene']['projected_data_window'].update(wavy_center_line=True),'yellow_returns':lambda d:d['generated_scene']['projected_data_window'].update(yellow_circular_graphic=True),'text_unsafe':lambda d:d['generated_scene']['projection_layout']['story_text_bounds'][0].update(x=500),'simon_motion_missing':lambda d:d['generated_scene']['final_motion_polish']['simon'].update(moving_acquisition=False),'simon_lock_missing':lambda d:d['generated_scene']['final_motion_polish']['simon'].update(completion_state=False),'bridge_travel_missing':lambda d:d['generated_scene']['final_motion_polish']['leo_zeph'].update(traveling_bridge_signal=False),'bridge_pulses_excess':lambda d:d['generated_scene']['final_motion_polish']['leo_zeph'].update(pulse_count=8),'bio_scan_missing':lambda d:d['generated_scene']['final_motion_polish']['biometrics'].update(scan_traversal=False),'architecture_changed':lambda d:d['generated_scene']['final_motion_polish'].update(architectural_changes=1),'overload_pulses_missing':lambda d:d['generated_scene']['node_overload_refinement'].update(r6_pulse_events=0),'cell_breathing_excess':lambda d:d['generated_scene']['background_cells'].update(breathing_count=20),'green_weak':lambda d:d['generated_scene']['background_cells'].update(green_emphasis=.1),'projection_too_unstable':lambda d:d['generated_scene']['projection_physicality'].update(brightness_variation_max=.2),'text_jitter':lambda d:d['generated_scene']['projection_physicality'].update(text_transform_jitter=3),'record_holds_missing':lambda d:d['generated_scene']['record_transitions'].update(completion_holds=0),'multiple_surfaces':lambda d:d['generated_scene']['record_transitions'].update(same_surface=False),'cta_packets_missing':lambda d:d['generated_scene']['cta'].update(energy_packets_visible=False),'cta_hold_short':lambda d:d['generated_scene']['cta'].update(final_hold=.5),'center_cable_returns':lambda d:d['generated_scene']['depth_system'].update(center_foreground_cable=True)}
 with tempfile.TemporaryDirectory(prefix='mf006r6-failure-') as td:
  for name,mutate in m.items():
   data=copy.deepcopy(base);mutate(data);layout=Path(td)/f'{name}.json';result=Path(td)/f'{name}-result.json';motion=Path(td)/f'{name}-motion.json';layout.write_text(json.dumps(data));cmd=['python3',str(Path(a.repo_root)/'scripts/validate_mf006r6_production.py'),'--project-root',a.repo_root,'--fixture',a.fixture,'--layout',str(layout),'--execution',a.execution,'--music-stem',a.music_stem,'--music-reference',a.music_reference,'--sfx-audio',a.sfx_audio,'--sfx-report',a.sfx_report,'--mix',a.mix,'--media',a.media,'--contract',a.contract,'--output',str(result),'--motion-timeline',str(motion)];run=subprocess.run(cmd,capture_output=True,text=True);rejected=run.returncode!=0 and json.loads(result.read_text()).get('result')=='FAIL';cases.append({'case':name,'expected':'REJECT','actual':'REJECT' if rejected else 'ACCEPT','result':'PASS' if rejected else 'FAIL'})
 report={'slice':'MF-006R6','case_count':len(cases),'cases':cases,'result':'PASS' if all(c['result']=='PASS' for c in cases) else 'FAIL'};Path(a.output).write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));return 0 if report['result']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
