#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); export PATH="${HOME}/.local/bin:${PATH}"; godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006r2-unknown-process.json; grammar=$repo_root/config/visual-grammar.json; artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r2}; report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r2}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir"; work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX"); frames=$work_dir/frames; mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]]; then find "$work_dir" -depth -delete; fi; }; trap cleanup EXIT
fail_result(){ code=$?; python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R2','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R2 EXECUTION FAILED\n' >&2; exit "$code"; }; trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006R2\n========================\n\nCONTRACT\n'
python3 "$repo_root/scripts/validate_mf006r2_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006R2","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"
printf '[PASS] approved Unknown Process copy, projected-only center, destination, music\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'

python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json; python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text()); d['music']['fade_in']=0; d['music']['fade_out']=0; pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 18.3 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 180 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 549
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R2 --final-lufs -16 --final-true-peak -1.5 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 18.3 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R2 --duration-min 18.1 --duration-max 18.5 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r2_production.py" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"

for specification in '000000 00-path-start' '000015 01-path-draw' '000036 02-charge' '000046 03-overload' '000054 04-burst' '000070 05-title-seed' '000100 06-unfold' '000132 07-hunted' '000210 08-targets' '000285 09-biometric' '000360 10-collapse' '000390 11-reclaimed' '000465 12-cta-start' '000525 13-cta-hold'; do set -- $specification; cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png"; done
for index in $(seq 0 19); do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*.91)*30+.5)}'); cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png"; done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=5x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=7x2:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r2-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$artifact_dir" "$report_dir" <<'PY'
import json,pathlib,sys
a=pathlib.Path(sys.argv[1]); r=pathlib.Path(sys.argv[2]); load=lambda p:json.loads(p.read_text()); production=load(a/'validation/production.json'); contract=load(a/'validation/contract.json'); media=load(a/'validation/output.json'); sfx=load(a/'validation/sfx.json'); assert production['result']=='PASS_WITH_BLOCKER' and production['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS'
result={'slice':'MF-006R2','selected_book':{'title':'Unknown Process','canonical_author':'Robert C. Blanzy','display_author':'R.C. Blanzy','series':'The Second Presence','book_number':1},'center_concept':'projected codex generated by central node/emitter','physical_standing_book_used':False,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','release_eligible':False,'blockers':contract['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'duration_seconds':18.3,'background_accent_ratio':10/54,'depth_layers':4,'renderer_implementation_files_changed':4,'renderer_architecture_changes':0,'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'}; (r/'result.json').write_text(json.dumps(result,indent=2)+'\n')
(r/'projection-notes.md').write_text('''# MF-006R2 Projection Notes\n\nThe R1 physical standing book and mechanical cradle are removed. The burst emits the title first; the title plane then unfolds into three luminous, scan-lined codex surfaces. A compact node-coupled emitter supplies a projection cone and rays. Story beats use continuously moving scan lines, pixel assembly, symbols, different compositions, and environmental response. The codex collapses into 64 fragments, compresses into the node, and returns through the original paths.\n''')
(r/'background-color-notes.md').write_text('''# MF-006R2 Background Color Notes\n\nThe wall remains majority dark: 44 of 54 powered cells are dark and 10 receive low-opacity purple, green, blue, or cyan accents (18.5%). Selection is deterministic and irregular. Their pulse is slow and limited, with a slight central-charge response. Four depth layers combine wall panels, recessed halo falloff, circuit/projection content, motes, and near-lens cable silhouettes.\n''')
(r/'candidate-comparison.md').write_text('''# MF-006R2 Candidate Comparison\n\n| Dimension | R1 | R2 candidate A |\n|---|---|---|\n| Center | physical book on cradle | light-based codex emitted from node-coupled source |\n| Support | rails, clamps, contacts | compact subordinate projection coupler |\n| Pages | physical page surfaces | scan-lined planes, pixel assembly, symbols, energy sweeps |\n| Ending | physical book dissolves | projection compresses into node before path return |\n| Background | nearly uniform dark wall | restrained powered purple/green/blue/cyan cells |\n| Depth | wall/cables/motes | added falloff, projection cone, foreground parallax cables |\n| Audio | physical formation/page foley | projection emission, phase shifts, collapse signature |\n\nOnly candidate A was produced: it directly tests the rejected center concept. More variants should wait for human review to identify a meaningful projection-energy axis.\n''')
(r/'center-concept-review.md').write_text('''# MF-006R2 Center Concept Review\n\n## Agent pre-review\n\nThe center is no longer a book or presentation artifact sitting on a stand. It reads as luminous story geometry sourced from the node/emitter: visible cone, wire surfaces, scanlines, assembly fragments, continuous hover, and collapse-to-node motion establish that relationship. The distinct beat compositions reduce state-swap behavior.\n\n## Required human review\n\n**PENDING.** In particular: **Does the center now feel like a projected story artifact generated by the machine, rather than a book or slide object sitting in the scene?** Review all 21 brief questions against `artifacts/mf-006r2/candidate-a.mp4`. This report does not impersonate human approval.\n''')
(r/'evidence-summary.md').write_text('''# MF-006R2 Evidence Summary\n\nVisual/audio technical subgate: **PASS**. Eleven fail-closed negative safeguards: **PASS**. Production voice: **BLOCKED**. Human editorial: **PENDING**. Release: **NO**.\n\nR2 replaces the physical center with a projected codex generated from the central node and compact emitter. Three differentiated story projections, restrained powered background cells, four depth layers, collapse/reclaim/return logic, machine-built CTA, continuous approved music, and 12 synchronized projection/electrical cues validate. No cover image or physical standing book is used.\n\nRecommended next step: human center-concept review, then obtain the production voice. If the center still reads flat, refine plane rotation/parallax and projection-light interaction rather than returning to a physical book.\n''')
print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006R2 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL: PENDING\nRELEASE_ELIGIBLE: NO\n'
exit 3
