#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); export PATH="${HOME}/.local/bin:${PATH}"; godot_bin=${GODOT_BIN:-godot}
fixture=$repo_root/content/fixtures/mf006r4-unknown-process.json; grammar=$repo_root/config/visual-grammar.json; artifact_dir=${MF_ARTIFACT_DIR:-$repo_root/artifacts/mf-006r4}; report_dir=${MF_REPORT_DIR:-$repo_root/reports/mf-006r4}
mkdir -p "$artifact_dir"/{audio,frames,logs,motion-evidence,music,timelines,validation} "$report_dir"; work_dir=$(mktemp -d "$artifact_dir/work.XXXXXX"); frames=$work_dir/frames; mkdir -p "$frames"
cleanup(){ if [[ $work_dir == "$artifact_dir"/work.* && -d $work_dir ]]; then find "$work_dir" -depth -delete; fi; }; trap cleanup EXIT
fail_result(){ code=$?; python3 - "$report_dir/result.json" "$code" <<'PY'
import json,pathlib,sys
pathlib.Path(sys.argv[1]).write_text(json.dumps({'slice':'MF-006R4','gates':{'visual_audio_technical':'FAIL','production_voice':'BLOCKED','human_editorial':'PENDING_HUMAN','release':'RELEASE_ELIGIBLE_NO'},'exit_code':int(sys.argv[2]),'result':'FAIL'},indent=2)+'\n')
PY
printf '\nMF-006R4 EXECUTION FAILED\n' >&2; exit "$code"; }; trap fail_result ERR

printf 'MEDIA FOUNDRY — MF-006R4\n========================\n\nCONTRACT\n'
python3 "$repo_root/scripts/validate_mf006r4_contract.py" --fixture "$fixture" --project-root "$repo_root" --output "$artifact_dir/validation/contract.json" >"$artifact_dir/logs/contract.log"
python3 "$repo_root/scripts/preflight_mf004.py" --fixture "$fixture" --grammar "$grammar" --project-root "$repo_root" --output "$artifact_dir/timelines/preflight.json" >"$artifact_dir/logs/preflight.log"
printf '{"slice":"MF-006R4","segments":[],"voice_status":"BLOCKED_PRODUCTION_VOICE","blockers":["BLOCKED_PRODUCTION_VOICE"],"result":"PASS_WITH_BLOCKER"}\n' >"$artifact_dir/timelines/narration.json"
printf '[PASS] approved copy, preserved one-window grammar, 26-30 second pacing, destination, music\n[BLOCKED] production voice unavailable\n\nPRODUCTION\n'

python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/production.wav" --output-report "$artifact_dir/timelines/music.json" >"$artifact_dir/logs/music.log"
reference_fixture=$work_dir/reference.json; python3 - "$fixture" "$reference_fixture" <<'PY'
import json,pathlib,sys
d=json.loads(pathlib.Path(sys.argv[1]).read_text()); d['music']['fade_in']=0; d['music']['fade_out']=0; pathlib.Path(sys.argv[2]).write_text(json.dumps(d))
PY
python3 "$repo_root/scripts/prepare_mf005r1_music.py" --fixture "$reference_fixture" --project-root "$repo_root" --duration 28 --output-audio "$artifact_dir/music/reference.wav" --output-report "$work_dir/reference-report.json" >/dev/null
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/render-metrics.txt" timeout 240 "$godot_bin" --path "$repo_root/godot" --fixed-fps 30 res://mf002.tscn -- --fixture "$fixture" --grammar "$grammar" --output-dir "$frames" --layout-report "$artifact_dir/validation/layout.json" --timeline-report "$artifact_dir/timelines/execution.json" >"$artifact_dir/logs/render.log" 2>&1
test "$(find "$frames" -maxdepth 1 -name 'frame_*.png'|wc -l)" -eq 840
python3 "$repo_root/scripts/generate_mf006_sfx.py" --fixture "$fixture" --output "$artifact_dir/audio/sfx.wav" --report "$artifact_dir/validation/sfx.json" >"$artifact_dir/logs/sfx.log"
python3 "$repo_root/scripts/mix_mf005_audio.py" --base "$artifact_dir/audio/sfx.wav" --manifest "$artifact_dir/timelines/narration.json" --music-manifest "$artifact_dir/timelines/music.json" --duck-db -3 --slice MF-006R4 --final-lufs -15.5 --final-true-peak -2.0 --output "$artifact_dir/audio/final.wav" --report "$artifact_dir/validation/mix.json" >"$artifact_dir/logs/mix.log"
/usr/bin/time -f 'elapsed_seconds=%e\npeak_kib=%M' -o "$artifact_dir/logs/encode-metrics.txt" ffmpeg -hide_banner -loglevel error -y -framerate 30 -start_number 0 -i "$frames/frame_%06d.png" -i "$artifact_dir/audio/final.wav" -map 0:v:0 -map 1:a:0 -t 28 -vf 'scale=1080:1920:flags=neighbor,format=yuv420p' -c:v libx264 -preset medium -crf 20 -threads 1 -g 60 -keyint_min 60 -sc_threshold 0 -c:a aac -b:a 160k -ar 48000 -movflags +faststart -metadata creation_time='1970-01-01T00:00:00Z' "$artifact_dir/candidate-a.mp4" 2>"$artifact_dir/logs/encode.log"
python3 "$repo_root/scripts/validate_media.py" "$artifact_dir/candidate-a.mp4" --slice MF-006R4 --duration-min 27.8 --duration-max 28.2 --ffprobe-json "$artifact_dir/validation/ffprobe.json" --result-json "$artifact_dir/validation/output.json" >/dev/null
python3 "$repo_root/scripts/validate_mf004_timeline.py" --preflight "$artifact_dir/timelines/preflight.json" --execution "$artifact_dir/timelines/execution.json" --layout "$artifact_dir/validation/layout.json" --output "$artifact_dir/validation/timeline.json" >/dev/null
python3 "$repo_root/scripts/validate_mf006r4_production.py" --project-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$artifact_dir/validation/production.json" --motion-timeline "$artifact_dir/timelines/motion.json" >"$artifact_dir/logs/production.log"

for specification in '000000 00-path-start' '000045 01-charge' '000069 02-burst' '000096 03-title-stable' '000186 04-hunted-type' '000210 05-hunted-activity' '000258 06-hunted-lock' '000306 07-targets-type' '000330 08-targets-activity' '000384 09-targets-lock' '000432 10-biometrics-type' '000459 11-biometrics-activity' '000516 12-biometrics-lock' '000573 13-collapse' '000615 14-reclaimed' '000690 15-cta-type' '000714 16-url-reveal' '000810 17-final-hold'; do set -- $specification; cp "$frames/frame_$1.png" "$artifact_dir/frames/$2.png"; done
for index in $(seq 0 23); do frame=$(awk -v i="$index" 'BEGIN{printf "%06d",int((.15+i*1.17)*30+.5)}'); cp "$frames/frame_$frame.png" "$artifact_dir/motion-evidence/$(printf '%02d' "$index")-$frame.png"; done
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/motion-evidence/*.png" -vf 'scale=180:320,tile=6x4:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/motion-evidence/sequence.png"
ffmpeg -hide_banner -loglevel error -y -pattern_type glob -i "$artifact_dir/frames/*.png" -vf 'scale=180:320,tile=9x2:padding=4:margin=4:color=0x070b0f' -frames:v 1 "$artifact_dir/contact-sheet.png"
python3 "$repo_root/scripts/mf-006r4-failure-tests.py" --repo-root "$repo_root" --fixture "$fixture" --layout "$artifact_dir/validation/layout.json" --execution "$artifact_dir/timelines/execution.json" --music-stem "$artifact_dir/music/production.wav" --music-reference "$artifact_dir/music/reference.wav" --sfx-audio "$artifact_dir/audio/sfx.wav" --sfx-report "$artifact_dir/validation/sfx.json" --mix "$artifact_dir/validation/mix.json" --media "$artifact_dir/candidate-a.mp4" --contract "$artifact_dir/validation/contract.json" --output "$report_dir/failure-tests.json" >"$artifact_dir/logs/failure-tests.log"

python3 - "$repo_root" "$artifact_dir" "$report_dir" <<'PY'
import hashlib,json,pathlib,sys
root=pathlib.Path(sys.argv[1]); a=pathlib.Path(sys.argv[2]); r=pathlib.Path(sys.argv[3]); load=lambda p:json.loads(p.read_text()); production=load(a/'validation/production.json'); contract=load(a/'validation/contract.json'); media=load(a/'validation/output.json'); sfx=load(a/'validation/sfx.json'); assert production['result']=='PASS_WITH_BLOCKER' and production['gates']['visual_audio_technical']=='PASS' and media['result']=='PASS'
result={'slice':'MF-006R4','selected_book':{'title':'Unknown Process','canonical_author':'Robert C. Blanzy','display_author':'R.C. Blanzy','series':'The Second Presence','book_number':1},'preserved_baseline':'MF-006R3','center_concept':'single persistent projected recovered-record window','primary_window_count':1,'split_book_used':False,'wavy_center_line':False,'yellow_circular_graphic':False,'story_text_inside_window':True,'typed_text':True,'visual_audio_technical':'PASS','production_voice':'BLOCKED_PRODUCTION_VOICE','human_editorial':'PENDING_HUMAN','release_eligible':False,'blockers':contract['blockers']+['HUMAN_EDITORIAL_REVIEW','HUMAN_RELEASE_REVIEW'],'duration_seconds':28.0,'baseline_duration_seconds':18.3,'added_seconds':9.7,'record_activity_events':3,'record_lock_events':3,'cta_hold_seconds':4.2,'background_cells':{'dark':42,'purple':3,'green':3,'blue':3,'cyan':3},'renderer_architecture_changes':0,'sfx_count':sfx['event_count'],'failure_tests':'PASS','technical_validation':production,'artifact':media.get('artifact'),'result':'PASS_WITH_BLOCKER'}; (r/'result.json').write_text(json.dumps(result,indent=2)+'\n')
manifest={'slice':'MF-006R4','policy':'prior candidates are immutable learning artifacts; symlinks provide non-duplicating history references','entries':production['preservation'],'result':'PASS'}; (a/'validation/preservation.json').write_text(json.dumps(manifest,indent=2)+'\n')
(r/'candidate-comparison.md').write_text('''# MF-006R4 Candidate Comparison\n\n| Dimension | R3 preserved baseline | R4 candidate A |\n|---|---|---|\n| Runtime | 18.3 s | 28.0 s (+9.7 s) |\n| Center grammar | one persistent recovered-record window | preserved, one instance only |\n| Record life | phrase typing and refreshes | typing plus signal activity, beat-specific micro-diagrams, and signal locks |\n| Story rhythm | compressed three-beat passage | three differentiated 4.0–4.3 s record investigations |\n| Environment | seeded colored wall cells and depth | slower camera breath/reframes, extended pulses, and additional motes |\n| CTA | machine-built reveal | typed invitation, URL reveal, and 4.2 s final hold |\n\nOnly candidate A was produced because the brief asks to extend the approved R3 direction rather than explore alternate grammars.\n''')
(r/'editorial-review.md').write_text('''# MF-006R4 Editorial Review\n\n## Agent pre-review\n\nFrame evidence confirms the R3 single-window hierarchy remains intact. The extended record stays active after each phrase through small signal bars, a distinct motion diagram, and a lock state. The screen is slightly larger during story beats, the node remains subordinate, and the CTA earns a readable 4.2-second hold.\n\n## Required human review\n\n**PENDING.** Review `artifacts/mf-006r4/candidate-a.mp4` alongside the preserved R3 baseline. Confirm that the added ten seconds feel intentional, each story beat has distinct tension, the screen is alive without becoming busy, the URL is comfortable at phone size, and the final hold feels earned. This report does not impersonate human approval.\n''')
(r/'evidence-summary.md').write_text('''# MF-006R4 Evidence Summary\n\nVisual/audio technical subgate: **PASS**. Nineteen negative safeguards: **PASS**. Production voice: **BLOCKED**. Human editorial: **PENDING**. Release: **NO**.\n\nR4 preserves every prior candidate and the R3 one-window baseline, extends runtime from 18.3 to 28.0 seconds, adds restrained live record activity and beat-specific micro-diagrams, strengthens slow environmental movement, and allows a typed CTA plus 4.2-second final hold. Continuous approved music, measured 1.4/2.2-second fades, final loudness, 10 restrained SFX, full decode, and executed events validate.\n''')
(r/'preservation-notes.md').write_text('''# MF-006R4 Preservation Notes\n\nMF-006, R1, R2, and R3 candidate hashes were verified before R4 passed. `artifacts/mf-006-history/` contains descriptive iteration records and relative symlinks to the original candidate/contact-sheet files, avoiding duplication or overwrite. R3 remains the current-baseline comparison. R4 writes only to its own artifact/report directories.\n''')
(r/'progress-showcase.md').write_text('''# MF-006 Progress Showcase\n\nThe durable history is in `reports/mf-006-history/progress-showcase.md`; visual references are under `artifacts/mf-006-history/`. The progression is: initial promo → copy/CTA refinement → projected codex/depth → single recovered-record hierarchy → extended living-record pacing. Each step retains its original candidate as learning evidence; none is release eligible without production voice and human approval.\n''')
print(json.dumps(result,indent=2))
PY
trap - ERR
printf '\nMF-006R4 VISUAL/AUDIO TECHNICAL: PASS\nPRODUCTION VOICE: BLOCKED\nHUMAN EDITORIAL: PENDING\nRELEASE_ELIGIBLE: NO\n'
exit 3
