#!/usr/bin/env python3
"""Prove MF-006R7 rejects composition-balance regressions."""
import argparse,copy,json,subprocess,tempfile
from pathlib import Path
def main():
 p=argparse.ArgumentParser()
 for n in ('repo_root','fixture','layout','execution','music_stem','music_reference','sfx_audio','sfx_report','mix','media','contract','output'):p.add_argument('--'+n.replace('_','-'),required=True)
 a=p.parse_args();base=json.loads(Path(a.layout).read_text());cases=[];m={'branch_missing':lambda d:d['generated_scene']['lower_right_composition'].update(secondary_branch_count=0),'branch_too_thick':lambda d:d['generated_scene']['lower_right_composition'].update(branch_thickness=5),'too_many_packets':lambda d:d['generated_scene']['lower_right_composition'].update(maximum_packet_count=6),'constant_motion':lambda d:d['generated_scene']['lower_right_composition'].update(packet_duty_cycle=.9),'wrong_direction':lambda d:d['generated_scene']['lower_right_composition'].update(direction='outward'),'cell_missing':lambda d:d['generated_scene']['lower_right_composition'].update(powered_cell_count=0),'cell_too_bright':lambda d:d['generated_scene']['lower_right_composition'].update(powered_cell_resting_alpha=.6),'negative_space_lost':lambda d:d['generated_scene']['lower_right_composition'].update(negative_space_ratio=.2),'second_focal_point':lambda d:d['generated_scene']['lower_right_composition'].update(second_focal_point=True),'overload_response_missing':lambda d:d['generated_scene']['lower_right_composition'].update(overload_response=False),'cta_response_missing':lambda d:d['generated_scene']['lower_right_composition'].update(cta_response=False),'camera_changed':lambda d:d['generated_scene']['lower_right_composition'].update(camera_unchanged=False)}
 with tempfile.TemporaryDirectory(prefix='mf006r7-failure-') as td:
  for name,mutate in m.items():
   data=copy.deepcopy(base);mutate(data);layout=Path(td)/f'{name}.json';result=Path(td)/f'{name}-result.json';motion=Path(td)/f'{name}-motion.json';layout.write_text(json.dumps(data));cmd=['python3',str(Path(a.repo_root)/'scripts/validate_mf006r7_production.py'),'--project-root',a.repo_root,'--fixture',a.fixture,'--layout',str(layout),'--execution',a.execution,'--music-stem',a.music_stem,'--music-reference',a.music_reference,'--sfx-audio',a.sfx_audio,'--sfx-report',a.sfx_report,'--mix',a.mix,'--media',a.media,'--contract',a.contract,'--output',str(result),'--motion-timeline',str(motion)];run=subprocess.run(cmd,capture_output=True,text=True);rejected=run.returncode!=0 and json.loads(result.read_text()).get('result')=='FAIL';cases.append({'case':name,'result':'PASS' if rejected else 'FAIL'})
 report={'slice':'MF-006R7','case_count':len(cases),'cases':cases,'result':'PASS' if all(x['result']=='PASS' for x in cases) else 'FAIL'};Path(a.output).write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));return 0 if report['result']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
