#!/usr/bin/env python3
"""Prove MF-006R8 rejects lower-right integration regressions."""
import argparse,copy,json,subprocess,tempfile
from pathlib import Path

def main():
 p=argparse.ArgumentParser()
 for n in ('repo_root','fixture','layout','execution','music_stem','music_reference','sfx_audio','sfx_report','mix','media','contract','output'):p.add_argument('--'+n.replace('_','-'),required=True)
 a=p.parse_args();base=json.loads(Path(a.layout).read_text());cases=[];m={'separate_branch_returns':lambda d:d['generated_scene']['lower_right_integration'].update(r7_separate_branch_removed=False),'hub_disconnected':lambda d:d['generated_scene']['lower_right_integration'].update(connects_directly_to_main_hub=False),'not_shared_collection':lambda d:d['generated_scene']['lower_right_integration'].update(uses_shared_circuit_collection=False),'not_shared_draw':lambda d:d['generated_scene']['lower_right_integration'].update(uses_shared_draw_logic=False),'dedicated_packets':lambda d:d['generated_scene']['lower_right_integration'].update(dedicated_packet_sequence=True),'corner_animation':lambda d:d['generated_scene']['lower_right_integration'].update(custom_corner_event_animation=True),'standalone_cell_returns':lambda d:d['generated_scene']['lower_right_integration'].update(powered_cell_count=1),'negative_space_lost':lambda d:d['generated_scene']['lower_right_integration'].update(negative_space_ratio=.2),'second_focal_point':lambda d:d['generated_scene']['lower_right_integration'].update(second_focal_point=True),'major_geometry_added':lambda d:d['generated_scene']['lower_right_integration'].update(new_major_geometry=1),'timing_changed':lambda d:d['generated_scene']['lower_right_integration'].update(timings_unchanged=False),'new_sfx_added':lambda d:d['generated_scene']['lower_right_integration'].update(new_sfx=1)}
 with tempfile.TemporaryDirectory(prefix='mf006r8-failure-') as td:
  for name,mutate in m.items():
   data=copy.deepcopy(base);mutate(data);layout=Path(td)/f'{name}.json';result=Path(td)/f'{name}-result.json';motion=Path(td)/f'{name}-motion.json';layout.write_text(json.dumps(data));cmd=['python3',str(Path(a.repo_root)/'scripts/validate_mf006r8_production.py'),'--project-root',a.repo_root,'--fixture',a.fixture,'--layout',str(layout),'--execution',a.execution,'--music-stem',a.music_stem,'--music-reference',a.music_reference,'--sfx-audio',a.sfx_audio,'--sfx-report',a.sfx_report,'--mix',a.mix,'--media',a.media,'--contract',a.contract,'--output',str(result),'--motion-timeline',str(motion)];run=subprocess.run(cmd,capture_output=True,text=True);rejected=run.returncode!=0 and json.loads(result.read_text()).get('result')=='FAIL';cases.append({'case':name,'result':'PASS' if rejected else 'FAIL'})
 report={'slice':'MF-006R8','case_count':len(cases),'cases':cases,'result':'PASS' if all(x['result']=='PASS' for x in cases) else 'FAIL'};Path(a.output).write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));return 0 if report['result']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
